language: java
jdk:
- openjdk8
- openjdk13
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- travis_wait ./gradlew check uberJar
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Jason Walonoski"
  - git config --local user.email "jwalonoski@mitre.org"
  - export TRAVIS_TAG=master-branch-latest
  - git tag -f $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: build/libs/synthea-with-dependencies.jar
  skip_cleanup: true
  on:
    tags: false
  overwrite: true
  prerelease: true
after_success:
- bash <(curl -s https://codecov.io/bash)
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
notifications:
  slack:
    rooms:
      secure: kkhOz7bqwfxC8x9Ml5RBBJJNID7u9ZW2VkG41bMENkp93E3+z+dlNV7vokJOQy6BqwDZn5BcsIJdhpXHONRWMZCcUzJEyiP9QkorWVoN6xtNaKwyRq9vDHeayvQ1Ks/JL6KoI4vTZqDYQgjZ4LgpKpB9resUxdwpW5dBrYulkEzpDogduIM64TGgnLxq6pgN78kyDlqIn7GlInSYouTYQyVtv+2eQUCVdKSpTIVh02abNmHlsEeJf4KtD4eMwYbN3xS0QTnKYjxnk/0KbUz+9c7EF671ttix3GNQbY2DvSXyhEg2TXXXUpopZO495Bl4eFnSmhskh7pizVRUAItgDv52AS67RGzVx+gVDNxG82QZyyvOywzzJxTXo1+I5W8CVsm27XdfWJgmSv6vBsF0ad/HpHRtl/CPo+wlwnVlXr+dv6HPsF9FSYH+SMl0J9KZ/VcXRCKlM1xklPhP9QY+jJY6oljH9l9tGzwoSfjDv+cNmZQPh5rkm6eAkfeqovE75t1aa2vEyllQIoJIZmtdH0kvnE5RO30RaA6BFCJ4Vmu2+5k7b+bpt5r1/ve5vGaIdycq4NDaFHTTKKVyjA4OOfiCZ7EM0zlfSKf5zwTUkeU8Qv6HK8h+lAUN9j/1Xer6yjsDv/9FWn0wZ1OuvYHvm2Ik4oM/eRJZw8N4pfT7BrY=
