synthea:

  start_date: <%= Time.now - 100.years %>
  end_date: <%= Time.now - 1.day %>
  time_step: 7 # days
  population: 
    area: 0.05 #13.9 # Bedford, MA # Default: 0.05
    birth_variance: 0.01
    daily_births_per_square_mile: <%= (ma_births_per_year = 73000.0)/(ma_square_miles=10554.0)/365.0 %>
  sequential: # sequential population generation... one at a time...
    # population is scaled to accurately represent MA (using a "true" population of 6,794,422)
    population: 1000
    multithreading: false  
    max_tries: 10 # max number of times it tries to create a person before it gives up (ie, nobody reached the target age)
  schedule:
    variance: 0.1
  lifecycle:
    # these growth numbers are based on internet data to produce average height/weight men and women
    # they are not "good numbers"
    growth_rate_male_average:   6.3   # centimeters per year
    growth_rate_male_stddev:    2     # centimeters per year
    growth_rate_female_average: 5.6   # centimeters per year
    growth_rate_female_stddev:  1.5   # centimeters per year
    weight_gain_male_average:   3.325 # kilograms per year
    weight_gain_male_stddev:    2     # kilograms per year
    weight_gain_female_average: 2.725 # kilograms per year
    weight_gain_female_stddev:  1     # kilograms per year
    # http://www.livestrong.com/article/142567-average-increase-weight-adults/
    adult_male_weight_gain:     0.034 # percent increase each year (where 1.0==100%)
    adult_female_weight_gain:   0.052 # percent increase each year (where 1.0==100%)
    adult_max_weight_age:       44    # age (years) when adults stop packing on weight

  metabolic:
    blood_glucose:
      normal:      5.7 # or less
      prediabetic: 6.5 # or less
      diabetic:    7.5 # or less
      severe:      9.0 # or less
    blood_pressure:
      normal:
        systolic: [100,139] # mmHg
        diastolic: [70,89]  # mmHg
      hypertensive:
        systolic: [140,200] # mmHg
        diastolic: [90,120] # mmHg
    hypertension:
      probability: 0.296 # (1.0==100%) http://www.cdc.gov/MMWr/preview/mmwrhtml/su6203a24.htm#Tab
      probability_given_diabetes: 0.594 #  (1.0==100%) http://www.cdc.gov/MMWr/preview/mmwrhtml/su6203a24.htm#Tab
    lipid_panel: #https://www.nlm.nih.gov/medlineplus/magazine/issues/summer12/articles/summer12pg6-7.html
      cholesterol:   [160,200,239,259,279,300] # mg/dL
      triglycerides: [100,150,199,499,550,600] # mg/dL
      hdl:           [ 80, 59, 40, 20, 10,  0] # mg/dL
    basic_panel:
      # Basic Metabolic Panel results: https://www.nlm.nih.gov/medlineplus/ency/article/003462.htm
      # Comprehensive Metabolic Panel results: https://www.nlm.nih.gov/medlineplus/ency/article/003468.htm
      normal:
        urea_nitrogen: [7,20] # mg/dL
        co2: [20,29] # mmol/L
        creatinine: [0.8,1.2] # mg/dL
        glucose: [64,100] # mg/dL
        chloride: [101,111] # mmol/L
        potassium: [3.7,5.2] # mEq/L
        sodium: [136, 144] # mEq/L
        calcium: [8.5,10.2] # mg/dL
      # http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/81260
      microalbumin_creatine_ratio: 
        normal: [0,17] # mg/g
        microalbuminuria_controlled: [17,30] # mg/g
        microalbuminuria_uncontrolled: [30,300] # mg/g
        proteinuria: [300,600] # mg/g
      # http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/8500
      # http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/8472
      creatinine_clearance:
        normal: # Creatine clearance test results: https://www.nlm.nih.gov/medlineplus/ency/article/003611.htm
          male: [77,160] # ml/min/BSA
          female: [56,161] # ml/min/BSA
        mild_kidney_damage: [60,90] # ml/min/BSA
        moderate_kidney_damage: [30,59] # ml/min/BSA
        severe_kidney_damage: [15,29] # ml/min/BSA
        esrd: [1,15] # ml/min/BSA
  cardiovascular:
    stroke:
      #https://www.heart.org/idc/groups/heart-public/@wcm/@sop/@smd/documents/downloadable/ucm_449858.pdf
      rate_20_39: [0.002, 0.007] #Prevalence of stroke by age and sex (Male, Female)
      rate_40_59: [0.019, 0.022]
      death: 0.15 #Strokes are fatal 10-20 percent of cases https://stroke.nih.gov/materials/strokechallenges.htm
    chd:
      #http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1647098/pdf/amjph00262-0029.pdf
      coronary_attack_risk: [0.042,0.015] #annual probability of coronary attack given history of angina (Male, Female)
      mi_proportion: 0.8 #Proportion of coronary attacks that are MI ,given history of CHD
      survive: 0.095 #http://cpr.heart.org/AHAECC/CPRAndECC/General/UCM_477263_Cardiac-Arrest-Statistics.jsp (0.095)
      bystander: 0.46 #http://cpr.heart.org/AHAECC/CPRAndECC/AboutCPRFirstAid/CPRFactsAndStats/UCM_475748_CPR-Facts-and-Stats.jsp 
    #http://circ.ahajournals.org/content/early/2014/12/18/CIR.0000000000000152.full.pdf
    sudden_cardiac_arrest: #annual probability of risk of sudden cardiac arrest and death. Used as risk of cardiac event w/o CHD
      risk: 0.00076
      death: 0.00069
    smoker: 0.161 # 16.1% of MA are smokers. http://www.cdc.gov/tobacco/data_statistics/state_data/state_highlights/2010/states/massachusetts/
  generic:
    log: false