synthea:
  exporter:
    ccda:
      export: true
      upload: null # not yet implemented
    fhir:
      export: true
      upload: null # url of the server, ex 'http://fhirserver.example.com:8080'
    html:
      export: true
    years_of_history: 5
    location: './output/'  # should either start with . for relative path or / for absolute
    folder_per_city: false
    subfolders_by_id_substring: true # if true, creates subfolders based on the first characters of the patient guid. this reduces the # of files in any single folder
  start_date: <%= Time.now - 100.years %>
  end_date: <%= Time.now - 1.day %>
  time_step: 7 # days
  population:
    area: 0.05 #13.9 # Bedford, MA # Default: 0.05
    birth_variance: 0.01
    daily_births_per_square_mile: <%= (ma_births_per_year = 73000.0)/(ma_square_miles=10554.0)/365.0 %>
    append_hash_to_person_names: true # If true, person names have a numeric hash appended to them to make them more obviously fake
  sequential: # sequential population generation... one at a time...
    # population is scaled to accurately represent MA (using a "true" population of 6,794,422)
    population: 100
    real_world_population: 6794422 #sum of the jsons in the config folder
    multithreading: false
    thread_pool_size:
    # numbers picked by experimentation on 2013 i5 mbp, may need to be tweaked on less powerful systems
    # consider SSD vs HDD, # of cpus/cores, memory usage, etc
      city_workers: 4
      generate_workers: 6
      export_workers: 10
    max_tries: 10 # max number of times it tries to create a person before it gives up (ie, nobody reached the target age)
    clean_output_each_run: true # clear out the output directory before running
    abort_on_exception: false # when true, if any thread throws an exception, abort the whole process
    enable_debug_logging: false
    debug_log_interval:
      generate: 100 # if enable_debug_logging is true, log every 100th patient generation
      export: 100 # if enable_debug_logging is true, log every 100th patient export
  schedule:
    variance: 0.1
  lifecycle:
    # The human twin birth rate in the United States rose 76% from 1980 through 2009, from 18.9 to 33.3 per 1,000 births.
    # - http://www.cdc.gov/nchs/data/databriefs/db80.pdf
    prevalence_of_twins:        0.02  # 20 per 1000
    # these growth numbers are based on internet data to produce average height/weight men and women
    # they are not "good numbers"
    growth_rate_male_average:   6.3   # centimeters per year
    growth_rate_male_stddev:    2     # centimeters per year
    growth_rate_female_average: 5.6   # centimeters per year
    growth_rate_female_stddev:  1.5   # centimeters per year
    weight_gain_male_average:   3.325 # kilograms per year
    weight_gain_male_stddev:    2     # kilograms per year
    weight_gain_female_average: 2.725 # kilograms per year
    weight_gain_female_stddev:  1     # kilograms per year
    # http://www.nhlbi.nih.gov/news/press-releases/2010/trials-use-technology-to-help-young-adults-achieve-healthy-weights
    # "Previous NHLBI research has shown that people aged 18-49 gain an average of 1-2 pounds each year"
    adult_weight_gain:          [1.0,2.0] # kilograms per year (this is more than 1-2 pounds, but we want obese people since we don't account for other factors effecting weight-gain)
    adult_max_weight_age:         49      # age (years) when adults stop packing on weight
    # http://www.aafp.org/afp/2014/0501/p718.html
    geriatric_weight_loss_age:    60      # age (years) when elderly begin to lose weight (between 60-70)
    geriatric_weight_loss:      [1.0,2.0] # kilograms per year (this is more than the citation, but our people are severely overweight)
  metabolic:
    blood_glucose:
      normal:      5.7 # or less
      prediabetic: 6.5 # or less
      diabetic:    7.5 # or less
      severe:      9.0 # or less
    blood_pressure:
      normal:
        systolic: [100,139] # mmHg
        diastolic: [70,89]  # mmHg
      hypertensive:
        systolic: [140,200] # mmHg
        diastolic: [90,120] # mmHg
    hypertension:
      probability: 0.296 # (1.0==100%) http://www.cdc.gov/MMWr/preview/mmwrhtml/su6203a24.htm#Tab
      probability_given_diabetes: 0.594 #  (1.0==100%) http://www.cdc.gov/MMWr/preview/mmwrhtml/su6203a24.htm#Tab
    lipid_panel: #https://www.nlm.nih.gov/medlineplus/magazine/issues/summer12/articles/summer12pg6-7.html
      cholesterol:   [160,200,239,259,279,300] # mg/dL
      triglycerides: [100,150,199,499,550,600] # mg/dL
      hdl:           [ 80, 59, 40, 20, 10,  0] # mg/dL
    basic_panel:
      # Basic Metabolic Panel results: https://www.nlm.nih.gov/medlineplus/ency/article/003462.htm
      # Comprehensive Metabolic Panel results: https://www.nlm.nih.gov/medlineplus/ency/article/003468.htm
      normal:
        urea_nitrogen: [7,20] # mg/dL
        co2: [20,29] # mmol/L
        creatinine: [0.8,1.2] # mg/dL
        chloride: [101,111] # mmol/L
        potassium: [3.7,5.2] # mEq/L
        sodium: [136, 144] # mEq/L
        calcium: [8.5,10.2] # mg/dL
      # http://www.cdc.gov/diabetes/prevention/pdf/point-of-care-prediabetes-identification-algorithm_tag508.pdf
      glucose: [64,100,125,200] # mg/dL [normal minimum,prediabetic,diabetic,max]
      # http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/81260
      microalbumin_creatine_ratio:
        normal: [0,17] # mg/g
        microalbuminuria_controlled: [17,30] # mg/g
        microalbuminuria_uncontrolled: [30,300] # mg/g
        proteinuria: [300,600] # mg/g
      # http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/8500
      # http://www.mayomedicallaboratories.com/test-catalog/Clinical+and+Interpretive/8472
      creatinine_clearance:
        normal: # Creatine clearance test results: https://www.nlm.nih.gov/medlineplus/ency/article/003611.htm
          male: [77,160] # ml/min/BSA
          female: [56,161] # ml/min/BSA
        mild_kidney_damage: [60,90] # ml/min/BSA
        moderate_kidney_damage: [30,59] # ml/min/BSA
        severe_kidney_damage: [15,29] # ml/min/BSA
        esrd: [1,15] # ml/min/BSA
  cardiovascular:
    stroke:
      #https://www.heart.org/idc/groups/heart-public/@wcm/@sop/@smd/documents/downloadable/ucm_449858.pdf
      rate_20_39: [0.002, 0.007] #Prevalence of stroke by age and sex (Male, Female)
      rate_40_59: [0.019, 0.022]
      death: 0.15 #Strokes are fatal 10-20 percent of cases https://stroke.nih.gov/materials/strokechallenges.htm
    chd:
      #http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1647098/pdf/amjph00262-0029.pdf
      coronary_attack_risk: [0.042,0.015] #annual probability of coronary attack given history of angina (Male, Female)
      mi_proportion: 0.8 #Proportion of coronary attacks that are MI ,given history of CHD
      survive: 0.095 #http://cpr.heart.org/AHAECC/CPRAndECC/General/UCM_477263_Cardiac-Arrest-Statistics.jsp (0.095)
      bystander: 0.46 #http://cpr.heart.org/AHAECC/CPRAndECC/AboutCPRFirstAid/CPRFactsAndStats/UCM_475748_CPR-Facts-and-Stats.jsp
    #http://circ.ahajournals.org/content/early/2014/12/18/CIR.0000000000000152.full.pdf
    sudden_cardiac_arrest: #annual probability of risk of sudden cardiac arrest and death. Used as risk of cardiac event w/o CHD
      risk: 0.00076
      death: 0.00069
  socioeconomic_status:
    weighting: # these should add up to 1.0
    # weighting and categories are inspired by the following but there are no specific hard numbers to point to
    #  http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1694190/pdf/amjph00543-0042.pdf
    # http://www.ncbi.nlm.nih.gov/pubmed/8122813
      income: 0.2
      education: 0.7
      occupation: 0.1
    categories:
      low: [0.0, 0.25]
      middle: [0.25, 0.66]
      high: [0.66, 1.0]
    values:
      education:
        less_than_hs: [0.0, 0.5]
        hs_degree: [0.1, 0.75]
        some_college: [0.3, 0.85]
        bs_degree: [0.5, 1.0]
  generic:
    log: false
  version_identifier: <%= `git rev-parse HEAD` %> # get the current git commit hash
  graphviz:
    output: './output/graphviz/'
