version: "2"
services:
  # mongodb container used only to support CCDA/HTML export
  # via the health-data-standards gem. Synthea will connect
  # to this container using the following connection string:
  # mongodb://mongo:27017. Docker automagically adds "mongo"
  # to /etc/hosts in the Synthea container.
  mongo:
    container_name: mongo
    image: "mongo:3.2"
    expose:
      - "27017"
  # Synthea will expect the usual commands at runtime.
  synthea:
    container_name: synthea
    image: synthetichealth/synthea:jruby
    build:
      # The build context is relative to docker-compose.yml.
      context: ../..
      # But the Dockerfile is relative to the build context.
      dockerfile: ./docker/jruby/Dockerfile
      args:
        # If defined, this will pick up the proxy from the
        # host's environment.
        http_proxy: "${http_proxy}"
        https_proxy: "${https_proxy}"
    volumes_from:
      # This data volume is created separately from the
      # docker-compose script. See: docker create -v
      - container:synthea_output:rw
    links:
      - mongo
    expose:
      - "27017"
    depends_on:
      - mongo
