name: io Pages Deployment 

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch and in the docs directory
  push:
    branches:
      - 'master'
    #paths:
    #  - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: "Install Python Packages"
        run: pip install -r requirements.txt
        
      - name: "Run mkdocs to build website"
        run: mkdocs gh-deploy --force --clean --verbose
